# Generated by Django 5.2.16 on 2026-08-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_target', models.CharField(max_length=30, verbose_name='比較對象，例如 USD_TWD / TWII / SOX / VIX')),
                ('method', models.CharField(choices=[('pearson', 'Pearson'), ('spearman', 'Spearman'), ('lagged', 'Lagged Correlation'), ('rolling', 'Rolling Correlation')], max_length=20)),
                ('lag_days', models.IntegerField(blank=True, null=True, verbose_name='lagged/rolling 分析用的天數')),
                ('result_value', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_results', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '關聯分析結果',
                'unique_together': {('stock', 'compare_target', 'method', 'lag_days')},
            },
        ),
    ]
