# Generated by Django 5.2.16 on 2026-08-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_start', models.DateField(verbose_name='訓練資料起始日')),
                ('train_end', models.DateField(verbose_name='訓練資料結束日')),
                ('validation_start', models.DateField(verbose_name='驗證資料起始日')),
                ('validation_end', models.DateField(verbose_name='驗證資料結束日')),
                ('model_type', models.CharField(default='lightgbm', max_length=20, verbose_name='lightgbm 或 xgboost')),
                ('model_version', models.CharField(max_length=30, verbose_name='模型版本標籤，例如 v1_2018_2024')),
                ('status', models.CharField(choices=[('pending', '排隊中'), ('running', '訓練中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('auc', models.FloatField(blank=True, null=True)),
                ('pr_auc', models.FloatField(blank=True, null=True, verbose_name='PR-AUC，不平衡標籤建議優先看這個')),
                ('months_from_train_end', models.IntegerField(blank=True, null=True, verbose_name='驗證期起始月 與 訓練期結束月 相差幾個月')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '模型訓練紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, unique=True, verbose_name='股票代碼')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名稱')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='產業分類')),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True, verbose_name='流通在外股數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否仍在交易')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '個股基本資料',
            },
        ),
        migrations.CreateModel(
            name='StockChipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('foreign_net_buy', models.BigIntegerField(default=0, verbose_name='外資買賣超張數')),
                ('trust_net_buy', models.BigIntegerField(default=0, verbose_name='投信買賣超張數')),
                ('margin_balance', models.BigIntegerField(default=0, verbose_name='融資餘額張數')),
                ('short_balance', models.BigIntegerField(default=0, verbose_name='融券餘額張數')),
                ('source_name', models.CharField(max_length=30)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_data', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '個股籌碼面原始資料',
                'unique_together': {('stock', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='StockFeatureDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('ma20_slope', models.FloatField(blank=True, null=True)),
                ('ma60_slope', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('institutional_net_buy_ratio', models.FloatField(blank=True, null=True, verbose_name='法人買賣超佔近20日成交量比例 (%)')),
                ('margin_usage_ratio', models.FloatField(blank=True, null=True, verbose_name='資券使用率 (%)')),
                ('excess_return_vs_benchmark', models.FloatField(blank=True, null=True, verbose_name='相對大盤超額報酬')),
                ('beta_vs_benchmark', models.FloatField(blank=True, null=True)),
                ('usd_twd_change_rate', models.FloatField(blank=True, null=True, verbose_name='美元兌台幣匯率月變動率')),
                ('sox_change_rate', models.FloatField(blank=True, null=True, verbose_name='費城半導體指數（^SOX）月變動率')),
                ('vix_level_percentile', models.FloatField(blank=True, null=True, verbose_name='VIX 相對水位（歷史百分位）')),
                ('vix_change_rate', models.FloatField(blank=True, null=True, verbose_name='VIX 月變動率')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_features', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '個股日頻特徵',
                'unique_together': {('stock', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='StockFeatureMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='此特徵開始生效的日期（= 公告日期）')),
                ('revenue_mom', models.FloatField(blank=True, null=True)),
                ('revenue_yoy', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_features', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '個股月頻特徵',
                'unique_together': {('stock', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='StockLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='標籤起算日 t')),
                ('return_20', models.FloatField(verbose_name='Return20 = (P(t+20)-P(t))/P(t)')),
                ('label', models.SmallIntegerField(verbose_name='0 或 1')),
                ('label_version', models.CharField(default='mvp', max_length=20, verbose_name='標籤版本：mvp（單一門檻）或 advanced（雙關卡）')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '股票標籤',
                'unique_together': {('stock', 'trade_date', 'label_version')},
            },
        ),
        migrations.CreateModel(
            name='StockMonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_month', models.DateField(verbose_name='營收所屬月份（該月第一天）')),
                ('announcement_date', models.DateField(verbose_name='實際公告日期，特徵對齊必須用這欄')),
                ('revenue_amount', models.BigIntegerField()),
                ('mom_growth', models.FloatField(blank=True, null=True, verbose_name='月增率 MoM')),
                ('yoy_growth', models.FloatField(blank=True, null=True, verbose_name='年增率 YoY')),
                ('source_name', models.CharField(max_length=30)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_revenue', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '個股月營收',
                'unique_together': {('stock', 'revenue_month')},
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('predicted_probability', models.FloatField(verbose_name='模型預測為1的機率')),
                ('predicted_label', models.SmallIntegerField()),
                ('model_version', models.CharField(max_length=30, verbose_name='模型版本，供之後做版本管理')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '股票預測結果',
                'unique_together': {('stock', 'trade_date', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='原始收盤價')),
                ('adjusted_close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='還原收盤價（計算 Return20 一律用這欄）')),
                ('volume', models.BigIntegerField(default=0, verbose_name='成交量')),
                ('source_name', models.CharField(max_length=30, verbose_name='資料來源，例如 FinMind / yfinance')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': '個股日線行情',
                'indexes': [models.Index(fields=['stock', 'trade_date'], name='stocks_stoc_stock_i_9618de_idx')],
                'unique_together': {('stock', 'trade_date')},
            },
        ),
    ]
