# Generated by Django 5.2.16 on 2026-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='label_version',
            field=models.CharField(default='mvp', max_length=20, verbose_name='mvp 或 advanced，需對應 StockLabel.label_version'),
        ),
        migrations.AddField(
            model_name='modeltrainingrun',
            name='model_file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='訓練完成後的模型檔案路徑'),
        ),
        migrations.AddField(
            model_name='modeltrainingrun',
            name='stock_codes',
            field=models.CharField(blank=True, max_length=500, verbose_name='訓練用的股票代碼，逗號分隔；留空代表使用資料庫內全部股票'),
        ),
    ]
