# Generated by Django 5.2.16 on 2026-08-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_modeltrainingrun_label_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='hyperparams',
            field=models.JSONField(blank=True, default=dict, verbose_name='訓練用的超參數，例如 n_estimators/learning_rate/num_leaves/max_depth'),
        ),
    ]
