# Generated by Django 5.2.16 on 2026-08-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_modeltrainingrun_hyperparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='auc_std',
            field=models.FloatField(blank=True, null=True, verbose_name='N次訓練的AUC標準差，越小代表結果越穩定'),
        ),
        migrations.AddField(
            model_name='modeltrainingrun',
            name='n_repeats',
            field=models.IntegerField(default=1, verbose_name='重複訓練次數（不同亂數種子），統計上建議 >1'),
        ),
        migrations.AddField(
            model_name='modeltrainingrun',
            name='pr_auc_std',
            field=models.FloatField(blank=True, null=True, verbose_name='N次訓練的PR-AUC標準差'),
        ),
    ]
