# Generated by Django 5.2.17 on 2026-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_modeltrainingrun_auc_std_modeltrainingrun_n_repeats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='bias_ma20',
            field=models.FloatField(blank=True, null=True, verbose_name='股價相對於 MA20 的乖離率'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='bias_ma60',
            field=models.FloatField(blank=True, null=True, verbose_name='股價相對於 MA60 的乖離率'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='inst_accel',
            field=models.FloatField(blank=True, null=True, verbose_name='籌碼加速度（近5日日均買超 / 近20日日均買超）'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='inst_net_buy_20d',
            field=models.FloatField(blank=True, null=True, verbose_name='外資與投信近20個交易日累計買賣超總和'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='macd_monthly',
            field=models.FloatField(blank=True, null=True, verbose_name='月線層級的MACD指數（EMA12-EMA26）'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='margin_mom',
            field=models.FloatField(blank=True, null=True, verbose_name='融資餘額相較於20個交易日前的月變化率 (MoM)'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='rs_vs_sox',
            field=models.FloatField(blank=True, null=True, verbose_name='個股對費半的相對強弱度（個股20日漲跌幅 - 費半20日漲跌幅）'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='rsi_diff_3d',
            field=models.FloatField(blank=True, null=True, verbose_name='日線級別14日RSI在近3天的增減變化量'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='rsi_monthly',
            field=models.FloatField(blank=True, null=True, verbose_name='月線層級的14個月RSI指數'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='sox_mom',
            field=models.FloatField(blank=True, null=True, verbose_name='費城半導體指數的20日累積漲跌幅'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='usd_twd',
            field=models.FloatField(blank=True, null=True, verbose_name='對齊交易日後的美元兌台幣匯率'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='vix',
            field=models.FloatField(blank=True, null=True, verbose_name='對齊交易日後的VIX恐慌指數'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='vol_ratio_5_20',
            field=models.FloatField(blank=True, null=True, verbose_name='量能比（5日平均成交量 / 20日平均成交量）'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='volatility_20d',
            field=models.FloatField(blank=True, null=True, verbose_name='近20個交易日每日對數報酬率的年化波動率'),
        ),
    ]
