# Generated by Django 5.2.17 on 2026-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stockfeaturedaily_bias_ma20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='model_version',
            field=models.CharField(max_length=100, verbose_name='模型版本標籤，例如 v1_2018_2024'),
        ),
    ]
