# Generated by Django 5.2.17 on 2026-08-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_modeltrainingrun_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprediction',
            name='model_version',
            field=models.CharField(max_length=100, verbose_name='模型版本，供之後做版本管理'),
        ),
    ]
