# Generated by Django 5.2.17 on 2026-08-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stockprediction_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='label_version',
            field=models.CharField(default='advanced', max_length=20, verbose_name='mvp 或 advanced（預設），需對應 StockLabel.label_version'),
        ),
        migrations.AlterField(
            model_name='stocklabel',
            name='label_version',
            field=models.CharField(default='advanced', max_length=20, verbose_name='標籤版本：mvp（單一門檻）或 advanced（雙關卡，預設）'),
        ),
    ]
