# Generated by Django 5.2.17 on 2026-08-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_modeltrainingrun_label_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='etf_premium_chg_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='ETF 折溢價率相較 5 日前的變化 (百分點)'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='etf_premium_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='ETF 折溢價率 (%)＝(收盤價－淨值)/淨值×100，正為溢價、負為折價'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='etf_premium_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='ETF 折溢價率近 5 日平均 (%)'),
        ),
        migrations.AddField(
            model_name='stockfeaturedaily',
            name='etf_premium_z20',
            field=models.FloatField(blank=True, null=True, verbose_name='ETF 折溢價率近 20 日 z-score（偏離近期常態的程度）'),
        ),
        migrations.CreateModel(
            name='EtfNavData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='資料日期')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='每單位淨值 (NAV)')),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='當日收盤價快照（可空；若空則以 StockPrice 補算折溢價）')),
                ('premium_discount_pct', models.FloatField(blank=True, null=True, verbose_name='折溢價率 (%)，正為溢價、負為折價')),
                ('source_name', models.CharField(default='csv_manual', max_length=30, verbose_name='資料來源')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_data', to='stocks.stockbasicinfo')),
            ],
            options={
                'verbose_name': 'ETF 淨值與折溢價',
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_etfn_stock_i_2aeb67_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
