# Generated by Django 5.2.17 on 2026-08-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockfeaturedaily_etf_premium_chg_5d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='feature_importance',
            field=models.JSONField(blank=True, default=list, verbose_name='特徵重要性（樹模型訓練完成後記錄；TFT 為空清單）'),
        ),
    ]
