# Generated by Django 5.2.17 on 2026-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_modeltrainingrun_feature_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='diagnostics',
            field=models.JSONField(blank=True, default=dict, verbose_name='誤導特徵診斷報告（diagnose_model 產出；未診斷過為空 dict）'),
        ),
    ]
