# Generated by Django 5.2.17 on 2026-09-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_modeltrainingrun_diagnostics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='模型檔名')),
                ('content', models.BinaryField(verbose_name='模型檔內容（joblib bytes）')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='檔案大小（bytes）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入庫時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='stocks.modeltrainingrun', verbose_name='對應的訓練紀錄')),
            ],
            options={
                'verbose_name': '模型檔入庫備份',
                'verbose_name_plural': '模型檔入庫備份',
            },
        ),
    ]
