# Generated by Django 5.2.17 on 2026-09-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_modelartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後心跳時間'),
        ),
    ]
