# Generated by Django 5.2.16 on 2026-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('stock_price', '股票行情'), ('stock_chip', '股票籌碼面'), ('stock_revenue', '股票月營收'), ('usd_twd', '美金匯率'), ('market_index', '跨市場指數'), ('trading_calendar', '交易日行事曆')], max_length=30)),
                ('target_code', models.CharField(blank=True, max_length=20, verbose_name='目標代碼，例如股票代碼；美金/大盤資料可留空')),
                ('status', models.CharField(choices=[('success_new_data', '成功，有寫入新資料'), ('success_no_new_data', '成功，已是最新狀態'), ('failed', '失敗')], max_length=20)),
                ('source_name', models.CharField(max_length=30, verbose_name='資料來源，例如 FinMind / yfinance / Yahoo Finance')),
                ('message', models.TextField(blank=True, verbose_name='說明或錯誤訊息')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '資料同步紀錄',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
