# Generated by Django 5.2.16 on 2026-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(unique=True)),
                ('is_trading_day', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '台股交易日行事曆',
                'ordering': ['calendar_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndexRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(choices=[('TWII', '加權指數 ^TWII'), ('SOX', '費城半導體指數 ^SOX'), ('VIX', '波動度指數 ^VIX')], max_length=10)),
                ('trade_date', models.DateField()),
                ('close_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_name', models.CharField(max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '跨市場指數資料',
                'unique_together': {('index_code', 'trade_date')},
            },
        ),
    ]
