# Generated by Django 5.2.16 on 2026-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdTwdRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(unique=True, verbose_name='日期')),
                ('close_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='收盤匯率')),
                ('source_name', models.CharField(default='Yahoo Finance', max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '美元兌台幣匯率',
                'ordering': ['-rate_date'],
            },
        ),
    ]
